diff -Nuar freecad-0.13.1830.orig/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_RadialPrism_3D.cpp freecad-0.13.1830/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_RadialPrism_3D.cpp
--- freecad-0.13.1830.orig/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_RadialPrism_3D.cpp	2013-02-02 19:09:17.000000000 +0200
+++ freecad-0.13.1830/src/3rdParty/salomesmesh/src/StdMeshers/StdMeshers_RadialPrism_3D.cpp	2013-08-25 16:48:41.589295757 +0300
@@ -44,7 +44,7 @@
 
 #include <BRepAdaptor_Curve.hxx>
 #include <BRepBuilderAPI_MakeEdge.hxx>
-#include <BRepTools.hxx>
+#include <BRepClass3d.hxx>
 #include <BRep_Tool.hxx>
 #include <TopExp_Explorer.hxx>
 #include <TopoDS.hxx>
@@ -161,7 +161,7 @@
 
   // get 2 shells
   TopoDS_Solid solid = TopoDS::Solid( aShape );
-  TopoDS_Shell outerShell = BRepTools::OuterShell( solid );
+  TopoDS_Shell outerShell = BRepClass3d::OuterShell( solid );
   TopoDS_Shape innerShell;
   int nbShells = 0;
   for ( TopoDS_Iterator It (solid); It.More(); It.Next(), ++nbShells )
@@ -401,7 +401,7 @@
 {
   // get 2 shells
   TopoDS_Solid solid = TopoDS::Solid( aShape );
-  TopoDS_Shell outerShell = BRepTools::OuterShell( solid );
+  TopoDS_Shell outerShell = BRepClass3d::OuterShell( solid );
   TopoDS_Shape innerShell;
   int nbShells = 0;
   for ( TopoDS_Iterator It (solid); It.More(); It.Next(), ++nbShells )
diff -Nuar freecad-0.13.1830.orig/src/Mod/Part/App/TopoShapeSolidPyImp.cpp freecad-0.13.1830/src/Mod/Part/App/TopoShapeSolidPyImp.cpp
--- freecad-0.13.1830.orig/src/Mod/Part/App/TopoShapeSolidPyImp.cpp	2013-02-02 19:09:17.000000000 +0200
+++ freecad-0.13.1830/src/Mod/Part/App/TopoShapeSolidPyImp.cpp	2013-08-25 16:48:41.591295757 +0300
@@ -24,7 +24,7 @@
 #include "PreCompiled.h"
 
 #include <BRepGProp.hxx>
-#include <BRepTools.hxx>
+#include <BRepClass3d.hxx>
 #include <GProp_GProps.hxx>
 #include <GProp_PrincipalProps.hxx>
 #include <BRepBuilderAPI_MakeSolid.hxx>
@@ -178,7 +178,7 @@
     TopoDS_Shell shell;
     const TopoDS_Shape& shape = getTopoShapePtr()->_Shape;
     if (!shape.IsNull() && shape.ShapeType() == TopAbs_SOLID)
-        shell = BRepTools::OuterShell(TopoDS::Solid(shape));
+        shell = BRepClass3d::OuterShell(TopoDS::Solid(shape));
     return Py::Object(new TopoShapeShellPy(new TopoShape(shell)),true);
 }
 
